name: CI

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@c95ae3725f6ebdd095f2bd19caed7ebc14435ba5 # v1.243.0
        with:
          bundler-cache: true
      - name: Run test
        run: bundle exec rubocop

  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@c95ae3725f6ebdd095f2bd19caed7ebc14435ba5 # v1.243.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install gem
        run: bundle exec rake install


  rubies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-head, '3.4', '3.3', '3.2']
        rails: [ '8.0', '7.2', '7.1']
        include:
          - ruby: '2.7'
            rails: '7.1'
          - ruby: '3.0'
            rails: '7.1'
          - ruby: '3.1'
            rails: '7.1'
          - ruby: '3.1'
            rails: '7.2'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@c95ae3725f6ebdd095f2bd19caed7ebc14435ba5 # v1.243.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run test
        run: bundle exec rake
